---
# roles/redis/tasks/main.yml

- name: Deploy Redis PVC
  kubernetes.core.k8s:
    state: present
    src: 'templates/redis-pvc.yaml'
    namespace: '{{ dev_namespace }}'

- name: Deploy Redis Service
  kubernetes.core.k8s:
    state: present
    src: 'templates/redis-master-cs.yaml'
    namespace: '{{ dev_namespace }}'

- name: Deploy Redis Master
  kubernetes.core.k8s:
    state: present
    src: 'templates/redis-master.yaml'
    namespace: '{{ dev_namespace }}'
