---
# roles/csi-drivers/tasks/main.yml

- name: Add the aws-ebs-csi-driver Helm repository
  kubernetes.core.helm_repository:
    name: aws-ebs-csi-driver
    repo_url: 'https://kubernetes-sigs.github.io/aws-ebs-csi-driver'
  when: (state | default('present')) == 'present'

- name: "{{ 'Install' if (state | default('present')) == 'present' else 'Uninstall' }} AWS EBS CSI Driver Helm chart"
  kubernetes.core.helm:
    name: aws-ebs-csi-driver
    chart_ref: aws-ebs-csi-driver/aws-ebs-csi-driver
    release_namespace: kube-system
    values:
      controller:
        serviceAccount:
          create: true
          name: ebs-csi-controller-sa
          annotations:
            'eks.amazonaws.com/role-arn': '{{ ebs_csi_driver_role_arn.value }}'
    state: "{{ state | default('present') }}"
    wait: true
    wait_timeout: 300s
  ignore_errors: "{{ (state | default('present')) == 'absent' }}"

- name: Add the aws-efs-csi-driver Helm repository
  kubernetes.core.helm_repository:
    name: aws-efs-csi-driver
    repo_url: 'https://kubernetes-sigs.github.io/aws-efs-csi-driver'
  when: (state | default('present')) == 'present'

- name: "{{ 'Install' if (state | default('present')) == 'present' else 'Uninstall' }} AWS EFS CSI Driver Helm chart"
  kubernetes.core.helm:
    name: aws-efs-csi-driver
    chart_ref: aws-efs-csi-driver/aws-efs-csi-driver
    release_namespace: kube-system
    values:
      controller:
        serviceAccount:
          create: true
          name: efs-csi-controller-sa
          annotations:
            'eks.amazonaws.com/role-arn': '{{ efs_csi_driver_role_arn.value }}'
    state: "{{ state | default('present') }}"
    wait: true
    wait_timeout: 300s
  ignore_errors: "{{ (state | default('present')) == 'absent' }}"
