---
# roles/storage/tasks/main.yml

- name: "{{ 'Ensure' if (state | default('present')) == 'present' else 'Remove' }} '{{ dev_namespace }}' namespace exists"
  kubernetes.core.k8s:
    name: '{{ dev_namespace }}'
    api_version: v1
    kind: Namespace
    state: "{{ state | default('present') }}"

- name: "{{ 'Deploy' if (state | default('present')) == 'present' else 'Remove' }} EFS StorageClass"
  kubernetes.core.k8s:
    state: "{{ state | default('present') }}"
    definition: "{{ lookup('template', 'storageClass.yaml') }}"

- name: "{{ 'Create' if (state | default('present')) == 'present' else 'Remove' }} resources from templated PV definitions"
  kubernetes.core.k8s:
    state: "{{ state | default('present') }}"
    definition: "{{ lookup('template', 'createpv.yaml.j2') | from_yaml_all }}"
