---
# roles/kafka/tasks/main.yml

- name: Delete existing Kafka resources to ensure re-application
  kubernetes.core.k8s:
    state: absent
    src: '{{ item }}'
    namespace: '{{ dev_namespace }}'
  loop:
    - 'templates/kafka-ui.yaml'
    - 'templates/kafka.yaml'
    - 'templates/kafka-cs.yaml'
    - 'templates/kafka-pdb.yaml'
  ignore_errors: true
  when: (state | default('present')) == 'present'

- name: "{{ 'Deploy' if (state | default('present')) == 'present' else 'Remove' }} Kafka PodDisruptionBudget"
  kubernetes.core.k8s:
    state: "{{ state | default('present') }}"
    src: 'templates/kafka-pdb.yaml'
    namespace: '{{ dev_namespace }}'

- name: "{{ 'Deploy' if (state | default('present')) == 'present' else 'Remove' }} Kafka Client Service"
  kubernetes.core.k8s:
    state: "{{ state | default('present') }}"
    src: 'templates/kafka-cs.yaml'
    namespace: '{{ dev_namespace }}'

- name: "{{ 'Deploy' if (state | default('present')) == 'present' else 'Remove' }} Kafka StatefulSet"
  kubernetes.core.k8s:
    state: "{{ state | default('present') }}"
    src: 'templates/kafka.yaml'
    namespace: '{{ dev_namespace }}'

- name: "{{ 'Deploy' if (state | default('present')) == 'present' else 'Remove' }} Kafka UI"
  kubernetes.core.k8s:
    state: "{{ state | default('present') }}"
    src: 'templates/kafka-ui.yaml'
    namespace: '{{ dev_namespace }}'
