---
# roles/mysql/tasks/main.yml

- name: "{{ 'Deploy' if (state | default('present')) == 'present' else 'Remove' }} MySQL for Redmine"
  kubernetes.core.k8s:
    state: "{{ state | default('present') }}"
    definition: "{{ lookup('template', 'mysql.yaml.j2') }}"
    namespace: '{{ dev_namespace }}'
