---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
  labels:
    app: kafka-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      containers:
        - name: kafka-ui
          image: provectuslabs/kafka-ui:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
              name: http
          env:
            - name: SERVER_PORT
              value: '8081'
            - name: KAFKA_CLUSTERS_0_NAME
              value: 'dev-cluster'
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: 'kafka-svc:9093'
            - name: KAFKA_CLUSTERS_0_ZOOKEEPER
              value: 'zk-svc:2181'
            - name: TZ
              value: 'Asia/Seoul'
          resources:
            limits:
              cpu: '0.5'
              memory: '512Mi'
            requests:
              cpu: '0.1'
              memory: '256Mi'
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 10
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-ui-svc
  labels:
    app: kafka-ui
spec:
  selector:
    app: kafka-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
      name: http
  type: ClusterIP
