apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-secret
type: Opaque
data:
  # elastic 사용자의 비밀번호를 base64로 인코딩해서 저장
  elastic-password: {{ vault_elastic_password | b64encode }}
  # CA 생성을 위한 비밀번호
  ca-password: {{ 'elasticsearch-ca-password' | b64encode }}
