apiVersion: v1
kind: Service
metadata:
  name: redis-master-cs
  labels:
    component: redis-master
spec:
  selector:
    component: redis-master
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 6379
  type: ClusterIP
