# zipkin.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipkin
  template:
    metadata:
      labels:
        app: zipkin
    spec:
      containers:
        - name: zipkin
          image: openzipkin/zipkin:latest
          ports:
            - containerPort: 9411
          resources:
            requests:
              memory: '512Mi'
              cpu: '500m'
            limits:
              memory: '1Gi'
              cpu: '1'
          env:
            - name: STORAGE_TYPE
              value: 'mem' # 메모리 기반 스토리지 사용 (필요 시 cassandra, elasticsearch 등으로 변경)
---
apiVersion: v1
kind: Service
metadata:
  name: zipkin
spec:
  type: ClusterIP
  selector:
    app: zipkin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9411
