---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: 'Delete Airflow resources'
      kubernetes.core.k8s:
        state: absent
        src: '{{ item }}'
        namespace: dev-system
      loop:
        - 'roles/airflow/templates/token_updater_deployment.yaml.j2'
        - 'roles/airflow/templates/pod_template.yaml.j2'
        - 'roles/airflow/templates/api_service_secrets.yaml.j2'
        - 'roles/airflow/templates/airflow_service.yaml.j2'
        - 'roles/airflow/templates/airflow_service_rbac.yaml.j2'
        - 'roles/airflow/templates/airflow_service_init.yaml.j2'

    # - name: "Delete PostgreSQL resources"
    #   kubernetes.core.k8s:
    #     state: absent
    #     src: "roles/postgresql/templates/postgresql.yaml"
    #     namespace: dev-system
