---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: 'Delete Elasticsearch resources'
      kubernetes.core.k8s:
        state: absent
        src: '{{ item }}'
        namespace: '{{ dev_namespace }}'
      loop:
        - 'roles/elasticsearch/templates/es-master.yaml'
        - 'roles/elasticsearch/templates/es-master-cs.yaml'
        - 'roles/elasticsearch/templates/es-master-configmap.yaml'
        - 'roles/elasticsearch/templates/es-data1.yaml'
        - 'roles/elasticsearch/templates/es-data1-cs.yaml'
        - 'roles/elasticsearch/templates/es-data1-configmap.yaml'
        - 'roles/elasticsearch/templates/es-data2.yaml'
        - 'roles/elasticsearch/templates/es-data2-cs.yaml'
        - 'roles/elasticsearch/templates/es-data2-configmap.yaml'
