---
apiVersion: v1
kind: Secret
metadata:
  name: adminer-postgres-secret
type: Opaque
data:
  postgres-host: 'cG9zdGdyZXM='
  postgres-port: 'NTQzMg=='
  postgres-user: 'cG9zdGdyZXM='
  postgres-password: 'cGFzczEyMzQ='
  postgres-db: 'eW91dHViZV9kYg=='
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
  labels:
    app: adminer
    component: database-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
        component: database-admin
    spec:
      containers:
        - name: adminer
          image: adminer:standalone
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: ADMINER_DEFAULT_SERVER
              value: 'postgres'
            - name: ADMINER_DESIGN
              value: 'pepa-linha-dark'
          resources:
            requests:
              memory: '64Mi'
              cpu: '50m'
            limits:
              memory: '128Mi'
              cpu: '100m'
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
---
apiVersion: v1
kind: Service
metadata:
  name: adminer
  labels:
    app: adminer
    component: database-admin
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app: adminer
