---
apiVersion: v1
kind: Service
metadata:
  name: redmine
  namespace: dev-system
spec:
  type: ClusterIP
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 3000
  selector:
    app: redmine
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redmine
  namespace: dev-system
spec:
  selector:
    matchLabels:
      app: redmine
  template:
    metadata:
      labels:
        app: redmine
    spec:
      containers:
        - name: redmine
          image: redmine
          env:
            - name: REDMINE_DB_MYSQL
              value: 'mysql'
            - name: REDMINE_DB_PASSWORD
              value: "{{ vault_redmine_db_password }}"
            - name: REDMINE_SECRET_KEY_BASE
              value: "{{ vault_redmine_secret_key }}"
          ports:
            - containerPort: 3000
